CREATE GLOBAL TEMPORARY TABLE DCADM.YSQK
 (
  AJBS         NUMBER NOT NULL,
  AJLX         VARCHAR2(4),
  ID           VARCHAR2(36) NOT NULL,
  REG_TIME     DATE NOT NULL,
  UPDATE_TIME  DATE NOT NULL,
  DEPT_CODE    VARCHAR2(20),
  APP_CODE     VARCHAR2(20),
  XH           NUMBER,
  JBFY         NUMBER,
  AH           VARCHAR2(50),
  AY           NUMBER,
  SPCX         NUMBER,
  LARQ         DATE,
  JARQ         DATE,
  JAFS         NUMBER,
  SXRQ         DATE,
  TQXALY       NUMBER,
  TQXARQ       DATE,
  SXFLWSBH     VARCHAR2(50),
  YCPLX        NUMBER,
  SXPJFYJQDWMC VARCHAR2(200)
 ) ON COMMIT DELETE ROWS;